# -*- coding: utf-8-*-

OBSERVATION_TRACKING_COMMAND_KEY = 'observation.tracking_command'
OBSERVATION_IMAGE_LEFT_KEY = 'observation.images.left'
OBSERVATION_IMAGE_RIGHT_KEY = 'observation.images.right'
OBSERVATION_GRAVITY_KEY = 'observation.gravity'
OBSERVATION_BASE_LIN_VEL_KEY = 'observation.base_lin_vel'
OBSERVATION_BASE_ANG_VEL_KEY = 'observation.base_ang_vel'
OBSERVATION_JOINT_POS_KEY = 'observation.joint_pos'
OBSERVATION_JOINT_VEL_KEY = 'observation.joint_vel'
OBSERVATION_RELATIVE_BASE_HEIGHT_KEY = 'observation.relative_base_height'
OBSERVATION_LEFT_ANKLE_WORLD_POS_KEY = 'observation.left_ankle_world_pos'
OBSERVATION_RIGHT_ANKLE_WORLD_POS_KEY = 'observation.right_ankle_world_pos'
OBSERVATION_LEFT_ANKLE_POS_KEY = 'observation.left_ankle_pos'
OBSERVATION_RIGHT_ANKLE_POS_KEY = 'observation.right_ankle_pos'
OBSERVATION_LEFT_ANKLE_COLLISION_KEY = 'observation.left_ankle_collision'
OBSERVATION_RIGHT_ANKLE_COLLISION_KEY = 'observation.right_ankle_collision'
OBSERVATION_ENV_TIMESTAMP_KEY = 'env_timestamp'
JOINT_ACTION_KEY = 'action'


ALL_OBSERVATION_KEY_LIST = [
    OBSERVATION_TRACKING_COMMAND_KEY,
    OBSERVATION_IMAGE_LEFT_KEY,
    OBSERVATION_IMAGE_RIGHT_KEY,
    OBSERVATION_GRAVITY_KEY,
    OBSERVATION_BASE_LIN_VEL_KEY,
    OBSERVATION_BASE_ANG_VEL_KEY,
    OBSERVATION_JOINT_POS_KEY,
    OBSERVATION_JOINT_VEL_KEY,
    OBSERVATION_RELATIVE_BASE_HEIGHT_KEY,
    OBSERVATION_LEFT_ANKLE_WORLD_POS_KEY,
    OBSERVATION_RIGHT_ANKLE_WORLD_POS_KEY,
    OBSERVATION_LEFT_ANKLE_POS_KEY,
    OBSERVATION_RIGHT_ANKLE_POS_KEY,
    OBSERVATION_LEFT_ANKLE_COLLISION_KEY,
    OBSERVATION_RIGHT_ANKLE_COLLISION_KEY,
    JOINT_ACTION_KEY,
]


FEATURE_OBSERVATION_KEY_LIST = [
    OBSERVATION_TRACKING_COMMAND_KEY,
    OBSERVATION_GRAVITY_KEY,
    OBSERVATION_BASE_LIN_VEL_KEY,
    OBSERVATION_BASE_ANG_VEL_KEY,
    OBSERVATION_JOINT_POS_KEY,
    OBSERVATION_JOINT_VEL_KEY,
    OBSERVATION_RELATIVE_BASE_HEIGHT_KEY,
    JOINT_ACTION_KEY,
]


OBSERVATION_DICT_KEY_ORIGINAL_DICT = 'original_dict'
OBSERVATION_DICT_KEY_TENSOR = 'tensor'

DEFAULT_CAMERA_RESOLUTION = (128, 128, 3)
