simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

env:
  save_dataset: False

tasks:
- type: "SingleInferenceTask"
  name: "h1_house"
  scene_asset_path: GRUtopia/assets/scenes/demo_house/demo_house.usd
  scene_scale: [0.01, 0.01, 0.01]
  env_num: 1
  offset_size: 1.0
  robots:
  - name: h1
    prim_path: "/World/h1"
    type: "HumanoidRobot"
    position: [5.58, -0.77, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    sensor_params:
    - name: "left_eye_camera"
      enable: false
    - name: "web_chat"
    sensor_params:
    - name: "right_eye_camera"
      enable: false
