simulator:
  physics_dt: 1/240
  rendering_dt: 1/240
  rendering_interval: 24

env:
  bg_type: null
  save_dataset: False
  force_override: False
  dataset_path: GRUtopia/data/train
  repo_id: sim_robot
  observation_dim: 70
  privileged_obs_shape: 18
  num_observation_history: 5
  num_actions: 19
  device: "cuda:0"
  episode_length_s: 120
  robot_per_inference_frames: 4
  reward_container_name: "EurekaReward"
  record_video: True
  save_video_interval: 25

tasks:
- type: "SingleInferenceTask"
  name: "h1_locomotion"
  env_num: 1
  offset_size: 1.0
  robots:
  - name: h1_0
    prim_path: "/World/h1_0"
    type: "HumanoidRobot"
    position: [10., .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "train_ppo"
  - name: h1_1
    prim_path: "/World/h1_1"
    type: "HumanoidRobot"
    position: [-10., .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "train_ppo"
  - name: h1_2
    prim_path: "/World/h1_2"
    type: "HumanoidRobot"
    position: [.0, 10., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "train_ppo"
  - name: h1_3
    prim_path: "/World/h1_3"
    type: "HumanoidRobot"
    position: [.0, -10., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "train_ppo"
  - name: h1_4
    prim_path: "/World/h1_4"
    type: "HumanoidRobot"
    position: [10., 10., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "train_ppo"
  - name: h1_5
    prim_path: "/World/h1_5"
    type: "HumanoidRobot"
    position: [10., -10., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "train_ppo"
  - name: h1_6
    prim_path: "/World/h1_6"
    type: "HumanoidRobot"
    position: [.0, .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "train_ppo"
  objects:
  - name: target_cube_0
    type: VisualCube
    prim_path: /World/target_cube_0
    position: [1.0, 0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
  - name: target_cube_1
    type: VisualCube
    prim_path: /World/target_cube_1
    position: [1.0, 1.0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
  - name: target_cube_2
    type: VisualCube
    prim_path: /World/target_cube_2
    position: [3.0, 4.0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
