simulator:
  physics_dt: 1/240
  rendering_dt: 1/240
  rendering_interval: 4

env:
  bg_type: null
  save_dataset: False
  force_override: False
  dataset_path: GRUtopia/data/output
  repo_id: sim_robot
  robot_per_inference_frames: 4

tasks:
- type: "SingleInferenceTask"
  name: "h1_locomotion"
  env_num: 1
  offset_size: 1.0
  robots:
  - name: h1
    prim_path: "/World/h1"
    type: "HumanoidRobot"
    position: [.0, .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "random_move"
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    sensor_params:
    - name: "camera"
      enable: False
    - name: "tp_camera"
      enable: False
  objects:
  - name: target_cube_0
    type: VisualCube
    prim_path: /World/target_cube_0
    position: [1.0, 0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
  - name: target_cube_1
    type: VisualCube
    prim_path: /World/target_cube_1
    position: [1.0, 1.0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
  - name: target_cube_2
    type: VisualCube
    prim_path: /World/target_cube_2
    position: [3.0, 4.0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
