simulator:
  physics_dt: 1/240
  rendering_dt: 1/240

env:
  bg_type: null
  save_dataset: True
  force_override: True
  dataset_path: GRUtopia/data/output
  repo_id: sim_robot

tasks:
- type: "SingleInferenceTask"
  name: "h1_locomotion"
  env_num: 1
  offset_size: 1.0
  robots:
  - name: h1_0
    prim_path: "/World/h1_0"
    type: "HumanoidRobot"
    position: [2., .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
  - name: h1_1
    prim_path: "/World/h1_1"
    type: "HumanoidRobot"
    position: [-2., .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
  - name: h1_2
    prim_path: "/World/h1_2"
    type: "HumanoidRobot"
    position: [.0, 2., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    sensor_params:
    - name: "camera"
      enable: False
    - name: "tp_camera"
      enable: False
  - name: h1_3
    prim_path: "/World/h1_3"
    type: "HumanoidRobot"
    position: [.0, -2., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    sensor_params:
    - name: "camera"
      enable: False
    - name: "tp_camera"
      enable: False
  - name: h1_4
    prim_path: "/World/h1_4"
    type: "HumanoidRobot"
    position: [2., 2., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    sensor_params:
    - name: "camera"
      enable: False
    - name: "tp_camera"
      enable: False
  - name: h1_5
    prim_path: "/World/h1_5"
    type: "HumanoidRobot"
    position: [2., -2., 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    sensor_params:
    - name: "camera"
      enable: False
    - name: "tp_camera"
      enable: False
  - name: h1_6
    prim_path: "/World/h1_6"
    type: "HumanoidRobot"
    position: [.0, .0, 1.05]
    scale: [1, 1, 1]
    controller_params:
    - name: "move_by_speed"
    - name: "joint_controller"
    - name: "move_to_point"
    - name: "move_along_path"
    - name: "rotate"
    - name: "move_with_keyboard"
    - name: "web_chat"
    sensor_params:
    - name: "camera"
      enable: False
    - name: "tp_camera"
      enable: False
  objects:
  - name: target_cube_0
    type: VisualCube
    prim_path: /World/target_cube_0
    position: [1.0, 0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
  - name: target_cube_1
    type: VisualCube
    prim_path: /World/target_cube_1
    position: [1.0, 1.0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
  - name: target_cube_2
    type: VisualCube
    prim_path: /World/target_cube_2
    position: [3.0, 4.0, 1.0]
    scale: [0.05015, 0.05015, 0.05015]
    color: [1.0, 0, 1.0]
